version: '3.9'

services:
  text_db:
    image: postgres
    container_name: db_java
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1112
      POSTGRES_DB: numbeer
    ports:
      - '5432:5432'
    networks:
      - text-network

  app:
    image: demo1
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1112
      DB_NAME: db
      DB_HOST: db:5432
    depends_on:
      - text_db
    networks:
      - text-network

networks:
  text-network:
    driver: bridge